# This is a basic workflow to help you get started with Actions

name: Android CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  watch:
    types: [started]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    if: github.repository_owner == github.actor
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: build apk
        run: |
          chmod +x gradlew
          ./gradlew aR
          APP_BUILD_APK=$(find $GITHUB_WORKSPACE/app/build -regex .*/release/.*.apk)
          echo "build apk:$APP_BUILD_APK"
        
